### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by alistairewj** [mit-eicu/eicu-website#26]
There are quite a few acronyms (svr, svri, pvr, etc) - might be worth having a glossary of terms. We should also define these terms in the tables' documentation where they appear.

**Comment by tompollard** [comment]
There was originally a glossary, but I removed it because it was empty. Have added it back.

**Comment by rincont** [comment]
I will start working on the glossary of terms.

Teresa

**Comment by tompollard** [comment]
Thanks Theresa - the page is looking good so I think we're okay to close this issue. We can continue to update the glossary as we go along.
