### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by rincont** [mit-eicu/eicu-website#30]
I am starting to work on this. Question: Do we need breif definitions or just acronyms and terms e.g. APACHE: acute physiology age chronic health evaluation 
APS: acute physiology score 
etc....

**Comment by alistairewj** [comment]
Acronyms and terms is a good start!

**Comment by tompollard** [comment]
Duplicate of https://github.com/mit-eicu/eicu-website/issues/26
